name: Production

on:
  push:
    branches: [main]

jobs:
  production:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Create package
        run: npm run package

      - name: Read Version
        id: version
        run: |
          VALUE=$(jq ".version" package.json)
          echo "value=$VALUE" >> "$GITHUB_OUTPUT"

      - name: Archive and compress output
        run: tar -czf ffmpeg-frontend-linux-v${{ steps.version.outputs.value }}.tar.gz -C ./out/ .

      - name: Create release
        run: gh release create v${{ fromJSON(steps.version.outputs.value) }} ffmpeg-frontend-linux-v${{ steps.version.outputs.value }}.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}
